[package]
name = "netflow_parser"
version = "0.1.0"
edition = "2021"
author = "michael.mileusnich@gmail.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.9.0"
nom = "7.1.3"
nom-derive = "0.10.1"
serde = { version = "1.0.166", features = ["derive"] }
insta = { version = "1.30.0", features = ["yaml"] }

[dev-dependencies]
insta = { version = "1.30.0", features = ["yaml"] }
serde_json = "1.0.100"
